app_home:
    path: /
    defaults: { _controller: AppBundle:Default:version }

app_version:
    path: /version
    defaults: { _controller: AppBundle:Default:version }

badge_index:
    path: /badge/{imageName}.svg
    defaults: { _controller: 'AppBundle:Badge:index' }
    requirements:
        imageName: '[0-9A-Za-z.-]+'
