services:
    jmleroux.micro_rest.version:
        class: JmLeroux\Components\Core\Version

    akeneo.badge.factory:
        class: '%badge_factory%'

    akeneo.badge.renderer:
        class: '%badge_renderer%'
